- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
    - name: user_name
      prompt: Please enter username
      private: false 

    - name: password
      prompt: Please enter your password
      private: true
  tasks:
   - name: print details
     ansible.builtin.debug:
      msg: " User Name: {{ 'user_name' }}, Password: {{ 'password' }} "
