- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
    - name: user name
      prompt: Please enter user name
      private: false 

    - name: password
      prompt: Please enter your password
      private: true
  tasks:
   - name: print details
     ansible.builtin.debug:
      msg: " User Name: {{ user  name }}, Password: {{ password }} "
