- name: packages installation
  hosts: local
  connection: local
  become: true 
  tasks:
  - name: install package
    ansible.builtin.package: 
      name: "{{item}}"
      state: present
    loop:
     - nginx
     - zip
     - mysql
