- name: packages installation
  hosts: local
  connection: local
  become: true 
  tasks:
   - name: install packages
     ansible.builtin.packages: 
      name: "{{ item }}"
      state: present
     loop:
     - nginx
     - zip
     - mysql
