- name: demo on functions
  hosts: local
  connection: local
  vars:
   topics: linux aws docker ansible teraform gitbash powershell 
   tagsmap:
    name: Ansible
    course: aws with DevSecOps
    project: roboshop
    duration: 4 MONTHS
    mode: online
   tagslist:
    [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "course",
            "value": "aws with DevSecOps"
        },
        {
            "key": "project",
            "value": "roboshop"
        },
        {
            "key": "duration",
            "value": "4 MONTHS"
        },
        {
            "key": "mode",
            "value": "online"
        }
    ]

  tasks: 
  - name: greetings
    ansible.builtin.debug:
     msg : 
       - " Hi Mansoor, {{Greeting | default('Good morning')}} "
       - " Hi Mansoor, {{Greeting | default('Got selected as devops engineer in NTT Data')}} "

  - name: convert string to list 
    ansible.builtin.debug:
     msg: "{{ topics | split }}"  # converts string into list

  - name: convert list to string
    ansible.builtin.debug:
     msg: "{{ tagsmap | dict2items }}"    # converts list to string
     
  - name: dict to list 
    ansible.builtin.debug:
     msg:"{{ tagslist | items2dict }}"  # converts dict to list  
