- name: demo on functions
  hosts: local
  connection: local
  tasks: 
  - name: greetings
    ansible.builtin.debug:
     msg : " Hi Mansoor, {{Greeting | default('Good morning')}} "
     msg : " Hi Mansoor, {{Greeting | default('Got selected as devops engineer in NTT Data')}} "
